public class arithmaticexception
{

    public static void main(String[] args) 
{
        try {
            int number = 0; 
            int result = 100 / number;
            System.out.println("Result: " + result);
        }

  catch (ArithmeticException e)
       {
            System.out.println("Error: Division by zero.");
        } 

  finally 
       {
            System.out.println("Finally block executed.");
        }

        System.out.println("End of program.");
    }
}
